/* ==========================================================================
   mc-data.js  —  the recipe data layer: a small index now, detail on demand
   --------------------------------------------------------------------------
   CI initiative 5, "The Instant-Open Data Layer".

   recipes-data.js is 1.04 MB and all three page types loaded it synchronously,
   in full, before anything painted — so opening ONE recipe parsed all 318. The
   repo already suspected this (window.__mcBoot exists purely to measure it,
   audit C-06) but nothing had acted on it.

   The split is generated by tools/build-data.js:
     • recipes-index.js   149 KB — every field a card, the planner, Home,
                          Browse, Favorites or a recipe header needs. Loaded
                          synchronously, exactly like recipes-data.js was.
                          13.9% of what a cold open used to parse.
     • recipes-detail-NN  16 shards, 33–70 KB — ingredients, instructions and
                          the description. Injected on demand, never blocking.

   **window.RECIPES keeps its shape, and that is what makes this safe.** Every
   entry is a real object built from the index with the detail fields simply
   ABSENT; _absorb() then assigns those fields onto the very same objects. So
   any reference a caller already captured — recipeById()'s result, a card's
   closure, a planner row — gains ingredients and instructions in place, with
   no re-fetch and no re-lookup. recipesIn(), recipeById(), MCGrocery, the week
   generator and user-recipes.js all keep working untouched against it.

   What callers DO have to do is wait, and there is no honest way around that:
   three shell features genuinely need the whole corpus (ingredient search, the
   "Use it up" reverse index, and the low-shopping pantry filter), so they call
   ensureAll() and re-render when it resolves. recipe.html needs exactly one
   shard, so it calls ensureDetail(id) and paints its header from the index in
   the meantime. hasDetail()/allReady() let a caller check synchronously rather
   than silently rendering an empty ingredient list — which is the one real
   failure mode this design introduces, and the reason those guards exist.

   User recipes (user-recipes.js) carry their detail inline and are merged into
   window.RECIPES at load, so they have no shard and are always ready.

   Exposed as window.MCData.
   ========================================================================== */
(function () {
  "use strict";
  if (window.MCData) return;

  var SHARDS = window.RECIPES_SHARDS || 16;

  // Per-shard state: 0 idle · 1 loading · 2 loaded. Waiters are resolved when
  // the shard's own script calls _absorb().
  var state = [], waiters = [];
  for (var i = 0; i < SHARDS; i++) { state.push(0); waiters.push([]); }

  /* ── build window.RECIPES from the index ──────────────────────────────
     Real objects, detail fields absent. Identity matters: _absorb() assigns
     onto these exact objects, so references captured before the detail lands
     see it appear. */
  var byId = {};
  var RECIPES = (window.RECIPES_INDEX || []).map(function (e) {
    var r = {};
    for (var k in e) if (Object.prototype.hasOwnProperty.call(e, k)) r[k] = e[k];
    byId[r.recipe_id] = r;
    return r;
  });
  window.RECIPES = RECIPES;

  // A recipe with no shard number is user-authored (merged in whole by
  // user-recipes.js) and therefore always complete.
  function shardFor(id) {
    var r = byId[id];
    return r && typeof r._s === "number" ? r._s : -1;
  }
  function hasDetail(id) {
    var r = byId[id] || null;
    if (!r) {
      // Not from the index at all — a user recipe pushed straight into RECIPES.
      return true;
    }
    if (typeof r._s !== "number") return true;
    return state[r._s] === 2;
  }
  function allReady() {
    for (var i = 0; i < SHARDS; i++) if (state[i] !== 2) return false;
    return true;
  }

  /* ── shard loading ──────────────────────────────────────────────────── */
  // A <script> tag rather than fetch(): it is served from the service worker's
  // cache-first path exactly like every other asset, and it still works from a
  // file:// origin, which fetch() does not (CLAUDE.md notes the app is opened
  // that way sometimes).
  function shardUrl(n) {
    return "recipes-detail-" + (n < 10 ? "0" : "") + n + ".js";
  }

  function loadShard(n) {
    return new Promise(function (resolve) {
      if (n < 0 || n >= SHARDS || state[n] === 2) { resolve(true); return; }
      waiters[n].push(resolve);
      if (state[n] === 1) return;                  // already in flight
      state[n] = 1;
      var s = document.createElement("script");
      s.src = shardUrl(n);
      s.async = true;
      s.onerror = function () {
        // Never hang a caller on a missing shard: reset so a later call can
        // retry, and resolve false so the guard can degrade instead of waiting.
        state[n] = 0;
        var ws = waiters[n]; waiters[n] = [];
        ws.forEach(function (w) { try { w(false); } catch (e) {} });
      };
      document.head.appendChild(s);
    });
  }

  // Called by each generated shard file as its only statement.
  function _absorb(n, map) {
    Object.keys(map).forEach(function (id) {
      var r = byId[id];
      if (!r) return;
      var d = map[id];
      for (var k in d) if (Object.prototype.hasOwnProperty.call(d, k)) r[k] = d[k];
    });
    state[n] = 2;
    var ws = waiters[n]; waiters[n] = [];
    ws.forEach(function (w) { try { w(true); } catch (e) {} });
  }

  function ensureDetail(id) {
    if (hasDetail(id)) return Promise.resolve(true);
    return loadShard(shardFor(id));
  }

  var allPromise = null;
  function ensureAll() {
    if (allReady()) return Promise.resolve(true);
    if (allPromise) return allPromise;
    var jobs = [];
    for (var i = 0; i < SHARDS; i++) jobs.push(loadShard(i));
    allPromise = Promise.all(jobs).then(function (results) {
      allPromise = null;
      return results.every(Boolean);
    });
    return allPromise;
  }

  // Convenience for a set of ids (the planner's grocery merge: only the shards
  // this week's meals actually touch, not the whole corpus).
  function ensureMany(ids) {
    var need = {};
    (ids || []).forEach(function (id) {
      var n = shardFor(id);
      if (n >= 0 && state[n] !== 2) need[n] = true;
    });
    var keys = Object.keys(need);
    if (!keys.length) return Promise.resolve(true);
    return Promise.all(keys.map(function (n) { return loadShard(+n); }))
      .then(function (r) { return r.every(Boolean); });
  }

  window.MCData = {
    SHARDS: SHARDS,
    hasDetail: hasDetail,
    allReady: allReady,
    ensureDetail: ensureDetail,
    ensureMany: ensureMany,
    ensureAll: ensureAll,
    byId: function (id) { return byId[id] || null; },
    _absorb: _absorb
  };
})();
