// Mike's Cookbook — Service Worker
// Relative-path precache so the app works at any GitHub Pages project subpath.
// The CACHE_URLS list is generated by tools/build-sw.py — do not edit by hand.

const CACHE_NAME = 'mc-cookbook-v31';

const CACHE_URLS = [
  /* AUTOGEN:URLS START */
  './',
  './index.html',
  './collection.html',
  './collection.js',
  './cookbook-home.js',
  './cookbook-nav.js',
  './cookbook-sw.js',
  './cookbook.css',
  './cookbook.js',
  './diagnostics.html',
  './icon.svg',
  './manifest.json',
  './mc-account.js',
  './mc-backup-status.js',
  './mc-bridge.js',
  './mc-cards.js',
  './mc-data.js',
  './mc-export.js',
  './mc-fav.js',
  './mc-grocery.js',
  './mc-install.js',
  './mc-recipe-form.js',
  './mc-search.js',
  './mc-supabase.js',
  './mc-sync.js',
  './mc-timers.js',
  './mc-units.js',
  './quick-tour-overview.html',
  './quick-tour.html',
  './recipe.html',
  './recipes-detail-00.js',
  './recipes-detail-01.js',
  './recipes-detail-02.js',
  './recipes-detail-03.js',
  './recipes-detail-04.js',
  './recipes-detail-05.js',
  './recipes-detail-06.js',
  './recipes-detail-07.js',
  './recipes-detail-08.js',
  './recipes-detail-09.js',
  './recipes-detail-10.js',
  './recipes-detail-11.js',
  './recipes-detail-12.js',
  './recipes-detail-13.js',
  './recipes-detail-14.js',
  './recipes-detail-15.js',
  './recipes-index.js',
  './tracker-barcode.js',
  './tracker-calc.js',
  './tracker-foodapi.js',
  './tracker-recipe.js',
  './tracker-store.js',
  './tracker.js',
  './user-recipes.js',
  /* AUTOGEN:URLS END */
];

self.addEventListener('install', (event) => {
  // Activate a new version immediately rather than waiting for a manual Refresh.
  // Paired with clients.claim() on activate and the page's controllerchange
  // reload, this guarantees fixes reach users on the next visit without a tap.
  self.skipWaiting();
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(CACHE_URLS))
  );
});

// The page asks the waiting worker to take over (user tapped Refresh), or a
// kitchen timer expired while the tab was in the background (mc-timers.js).
//
// The timer notification is deliberately posted BY THE PAGE rather than
// scheduled here: with no Push service and no backend, a service worker has no
// way to wake itself at a future instant. So this fires only while the document
// is still alive — a backgrounded tab, typically Android. When the OS has fully
// suspended the page (iOS with the screen locked) nothing fires, and the timer
// instead reports itself as already finished the moment the app is reopened,
// because mc-timers.js stores an absolute end instant rather than a countdown.
self.addEventListener('message', (event) => {
  const data = event.data;
  if (!data) return;
  if (data.type === 'SKIP_WAITING') self.skipWaiting();
  if (data.type === 'MC_TIMER_DONE') {
    event.waitUntil(
      self.registration.showNotification(data.title || '⏰ Time!', {
        body: data.body || "Mike's Cookbook",
        icon: './icon.svg',
        badge: './icon.svg',
        tag: 'mc-timer',            // one timer notification at a time
        renotify: true,
        vibrate: [200, 100, 200],
        data: { url: './index.html' }
      })
    );
  }
});

// Tapping the notification focuses the open app rather than opening a second
// copy of it — a cook mid-recipe does not want a fresh tab.
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((list) => {
      for (const client of list) {
        if ('focus' in client) return client.focus();
      }
      return self.clients.openWindow ? self.clients.openWindow('./index.html') : undefined;
    })
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k))
      ))
      .then(() => self.clients.claim())
  );
});

// HTML: stale-while-revalidate (audit LS-4, W-12). Serve the cached page
// INSTANTLY when we have one — navigations feel instant on flaky kitchen
// Wi-Fi instead of waiting up to 3s — and refresh the cache behind for next
// load. Cache-first is correct because this is a static site whose content
// only changes on a deploy, which bumps CACHE_NAME (the activate handler above
// purges the old cache and cookbook-sw.js reloads on controllerchange), so a
// new build always reaches the cook via the SW-version path. First visits
// (nothing cached) fall through to the network, then the app shell.
// Everything else: cache-first, then network (unchanged — already instant).
self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const isHTML = req.mode === 'navigate' ||
    (req.headers.get('accept') || '').includes('text/html');

  if (isHTML) {
    const revalidation = fetch(req).then((res) => {
      if (res && res.status === 200) {
        const copy = res.clone();
        caches.open(CACHE_NAME).then((c) => c.put(req, copy));
      }
      return res;
    }).catch(() => null);
    event.waitUntil(revalidation.catch(() => {}));
    event.respondWith(
      caches.match(req).then((cached) =>
        cached || revalidation.then((res) => res || caches.match('./index.html'))
      )
    );
    return;
  }

  event.respondWith(
    caches.match(req).then((cached) =>
      cached || fetch(req).then((res) => {
        const copy = res.clone();
        caches.open(CACHE_NAME).then((c) => c.put(req, copy));
        return res;
      }).catch(() => cached)
    )
  );
});
