// Mike's Cookbook — Service Worker
// Relative-path precache so the app works at any GitHub Pages project subpath.
// The CACHE_URLS list is generated by tools/build-sw.py — do not edit by hand.

const CACHE_NAME = 'mc-cookbook-v2';

const CACHE_URLS = [
  /* AUTOGEN:URLS START */
  './',
  './index.html',
  './collection.html',
  './collection.js',
  './cookbook-home.js',
  './cookbook-nav.js',
  './cookbook-sw.js',
  './cookbook.css',
  './cookbook.js',
  './icon.svg',
  './manifest.json',
  './recipe.html',
  './recipes-data.js',
  /* AUTOGEN:URLS END */
];

self.addEventListener('install', (event) => {
  // Note: we deliberately do NOT skipWaiting() here. A new version installs and
  // waits, so the page can surface an "update available" toast and activate it
  // only when the user taps Refresh (see the SKIP_WAITING message below).
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(CACHE_URLS))
  );
});

// The page asks the waiting worker to take over (user tapped Refresh).
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k))
      ))
      .then(() => self.clients.claim())
  );
});

// HTML: network-first with a short timeout (kitchen Wi-Fi can be flaky), then
// fall back to cache. Everything else: cache-first, then network.
self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const isHTML = req.mode === 'navigate' ||
    (req.headers.get('accept') || '').includes('text/html');

  if (isHTML) {
    event.respondWith(
      Promise.race([
        fetch(req).then((res) => {
          const copy = res.clone();
          caches.open(CACHE_NAME).then((c) => c.put(req, copy));
          return res;
        }),
        new Promise((resolve) =>
          setTimeout(() => resolve(caches.match(req).then((m) => m || caches.match('./index.html'))), 3000)
        )
      ]).catch(() => caches.match(req).then((m) => m || caches.match('./index.html')))
    );
    return;
  }

  event.respondWith(
    caches.match(req).then((cached) =>
      cached || fetch(req).then((res) => {
        const copy = res.clone();
        caches.open(CACHE_NAME).then((c) => c.put(req, copy));
        return res;
      }).catch(() => cached)
    )
  );
});
