/* ==========================================================================
   user-recipes.js  —  "My Recipes" (user-authored bonus recipes)
   --------------------------------------------------------------------------
   Lets a cook add their own recipes from the Home hub ("Add Recipe" module).
   These live in localStorage — there is no backend and no build step — but
   they are merged into the in-memory data layer so they behave like every
   built-in recipe: they appear in Categories, app-wide search, the weekly
   planner + smart grocery merge, Favorites, and on the recipe-detail page.

   They surface as a single "My Recipes" flagship card on the Recipes screen,
   sitting BELOW the three authored collections (Two Meals a Day, Kelli's,
   Carnivore). The card opens collection.html?c=my-recipes, reusing the normal
   collection list.

   Load order matters: include this file AFTER recipes-data.js and BEFORE the
   page controller (cookbook-home.js / cookbook.js / collection.js). At load
   it augments window.RECIPES and window.COLLECTIONS so the controllers see the
   merged data with no rendering changes required.

   Persistence (matches the app's mc-cookbook: namespace):
     • mc-cookbook:userrecipes — JSON array of full recipe objects.

   Storage shape: each saved recipe conforms to the same schema the rest of the
   app consumes (see recipes-data.js), with `source: "My Recipes"`, `user: true`,
   empty macro_profiles (the form is macro-free by design — the detail page
   simply omits the macro card), and serving_2 / serving_4 ingredient tiers
   generated by scaling the cook's authored amounts.
   ========================================================================== */
(function () {
  "use strict";

  var KEY            = "mc-cookbook:userrecipes";
  var SOURCE         = "My Recipes";
  var COLLECTION_ID  = "my-recipes";
  var ACCENT         = "#7D8C77";   // sage — distinct from the warm collections

  /* ── Persistence ──────────────────────────────────────────────────── */
  function load() {
    try {
      var arr = JSON.parse(localStorage.getItem(KEY) || "[]");
      return Array.isArray(arr) ? arr : [];
    } catch (e) { return []; }
  }
  function persist(arr) {
    try { localStorage.setItem(KEY, JSON.stringify(arr)); } catch (e) {}
  }

  /* ── Quantity scaling (mirrors cookbook.js scaleQuantity) ─────────────
     The cook authors amounts for one serving count; we generate the 2- and
     4-serving tiers the rest of the app expects by scaling each quantity.
     Non-numeric amounts ("to taste") pass through unchanged. */
  function prettyNumber(v) {
    var whole = Math.floor(v + 1e-9), frac = v - whole;
    var FRACTIONS = [[1 / 4, "1/4"], [1 / 3, "1/3"], [1 / 2, "1/2"], [2 / 3, "2/3"], [3 / 4, "3/4"]];
    var best = null, bestDiff = 0.06;
    for (var i = 0; i < FRACTIONS.length; i++) {
      var d = Math.abs(frac - FRACTIONS[i][0]);
      if (d < bestDiff) { best = FRACTIONS[i][1]; bestDiff = d; }
    }
    if (frac < 0.06) return String(whole);
    if (frac > 0.94) return String(whole + 1);
    if (best) return (whole > 0 ? whole + " " : "") + best;
    return String(Math.round(v * 100) / 100);
  }
  function scaleQuantity(qty, factor) {
    if (qty == null) return qty;
    var s = String(qty).trim();
    var m = s.match(/^(\d+)\s+(\d+)\/(\d+)$/);            // mixed "1 1/2"
    var val;
    if (m) val = parseInt(m[1], 10) + parseInt(m[2], 10) / parseInt(m[3], 10);
    else if ((m = s.match(/^(\d+)\/(\d+)$/))) val = parseInt(m[1], 10) / parseInt(m[2], 10);
    else if (/^-?\d*\.?\d+$/.test(s)) val = parseFloat(s);
    else return s;                                         // non-numeric → leave
    return prettyNumber(val * factor);
  }
  function scaleList(list, factor) {
    return list.map(function (ing) {
      return {
        item: ing.item, prep: ing.prep,
        quantity: factor === 1 ? ing.quantity : scaleQuantity(ing.quantity, factor),
        unit: ing.unit, category: ing.category
      };
    });
  }

  /* ── ID helpers ───────────────────────────────────────────────────── */
  function slugify(s) {
    return String(s || "").toLowerCase().trim()
      .replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40) || "recipe";
  }
  function uniqueId(base, taken) {
    var id = base, n = 2;
    while (taken[id]) { id = base + "-" + n; n++; }
    return id;
  }

  /* ── Build a schema-conformant recipe from raw form input ───────────── */
  // raw: { title, icon, dish_category, description, tags[], accent,
  //        prep_time_mins, cook_time_mins, base_serving,
  //        ingredients[ {item,quantity,unit,category,prep} ],
  //        steps[ {title, detail} ] }
  function build(raw) {
    var base = parseInt(raw.base_serving, 10) || 2;
    var ings = (raw.ingredients || []).filter(function (i) { return (i.item || "").trim(); })
      .map(function (i) {
        return {
          item: (i.item || "").trim(),
          prep: (i.prep || "").trim(),
          quantity: (i.quantity || "").trim(),
          unit: (i.unit || "").trim(),
          category: i.category || "Pantry"
        };
      });
    var steps = (raw.steps || []).filter(function (s) { return (s.detail || "").trim() || (s.title || "").trim(); })
      .map(function (s, idx) {
        return {
          step_number: idx + 1,
          title: (s.title || "").trim() || ("Step " + (idx + 1)),
          detail: (s.detail || "").trim()
        };
      });

    var taken = {};
    (window.RECIPES || []).forEach(function (r) { taken[r.recipe_id] = 1; });
    var id = uniqueId(slugify(raw.title), taken);

    return {
      recipe_id: id,
      title: (raw.title || "Untitled Recipe").trim(),
      category: "My Recipe",
      source: SOURCE,
      user: true,
      icon: (raw.icon || "🍽️").trim() || "🍽️",
      tags: (raw.tags || []).map(function (t) { return String(t).trim(); }).filter(Boolean),
      dish_category: raw.dish_category || "",
      description: (raw.description || "").trim(),
      prep_time_mins: parseInt(raw.prep_time_mins, 10) || 0,
      cook_time_mins: parseInt(raw.cook_time_mins, 10) || 0,
      native_serving: 2,
      accent: raw.accent || ACCENT,
      macro_profiles: { serving_2: {}, serving_4: {} },   // macro-free by design
      scaling_options: [2, 4],
      ingredients_by_serving: {
        serving_2: scaleList(ings, 2 / base),
        serving_4: scaleList(ings, 4 / base)
      },
      instructions: steps
    };
  }

  /* ── CRUD (each op keeps the live in-memory pool in sync) ───────────── */
  function add(raw) {
    var rec = build(raw);
    var arr = load();
    arr.push(rec);
    persist(arr);
    if (window.RECIPES && window.RECIPES.indexOf(rec) < 0) window.RECIPES.push(rec);
    return rec;
  }
  function remove(id) {
    var arr = load().filter(function (r) { return r.recipe_id !== id; });
    persist(arr);
    if (window.RECIPES) {
      for (var i = window.RECIPES.length - 1; i >= 0; i--) {
        if (window.RECIPES[i].recipe_id === id && window.RECIPES[i].user) window.RECIPES.splice(i, 1);
      }
    }
  }
  function count() { return load().length; }

  /* ── Merge into the data layer at load time ─────────────────────────── */
  function mergeIntoData() {
    if (!window.RECIPES) window.RECIPES = [];
    var have = {};
    window.RECIPES.forEach(function (r) { have[r.recipe_id] = 1; });
    load().forEach(function (r) { if (!have[r.recipe_id]) window.RECIPES.push(r); });

    if (!window.COLLECTIONS) window.COLLECTIONS = [];
    var exists = window.COLLECTIONS.some(function (c) { return c.id === COLLECTION_ID; });
    if (!exists) {
      window.COLLECTIONS.push({
        id: COLLECTION_ID,
        title: SOURCE,
        tag: "★ Collection · Your Kitchen",
        blurb: "Your own recipes — add cherished dishes and quick ideas to your " +
               "personal library, fully searchable and ready for the weekly planner.",
        designer: "✍️ Added by you",
        accent: ACCENT,
        icon: "📝",
        status: "live",
        source_match: SOURCE
      });
    }
  }

  mergeIntoData();

  window.MCUser = {
    KEY: KEY, SOURCE: SOURCE, COLLECTION_ID: COLLECTION_ID, ACCENT: ACCENT,
    load: load, add: add, remove: remove, count: count,
    build: build, slugify: slugify
  };
})();
