#!/usr/bin/env node
'use strict';
/* ==========================================================================
   build-data.js — splits the authored recipes-data.js into what a page
   actually needs to paint (an index) and what it only needs once the cook
   opens something (detail shards).

   CI initiative 5, "The Instant-Open Data Layer". recipes-data.js is 1.04 MB
   and every one of the three page types loaded it synchronously, in full,
   before anything rendered — so opening ONE recipe parsed all 318. The repo
   already suspected this: window.__mcBoot exists (audit C-06) purely to
   measure it, and recipe.html's own comment calls it "62% of the payload."

   Same contract as tools/build-sw.py, deliberately: recipes-data.js stays the
   single source of truth and is still the only file you edit to add a recipe,
   these outputs are generated, and `--check` fails CI when they are stale.

   Two measurements shaped the split, and both contradicted the initial plan:

   • `description` was going to live in the index. It's ~51 KB across the
     corpus and it is read in exactly ONE place — cookbook.js's About card on
     recipe.html (nothing else renders it, and recipesMatch() doesn't search
     it). So it's detail, and the index is ~26% smaller for noticing.

   • Sharding was going to be alphabetical by recipe_id. Recipe ids cluster
     hard on a few letters — "c" alone (chicken, chipotle, chocolate, chorizo…)
     is 211 KB, bigger than the whole index — so opening a chicken recipe would
     have pulled a fifth of the corpus. A djb2 hash spreads the same data
     across SHARDS evenly instead; the shard number is written onto each index
     entry as `_s` so the client never has to reimplement the hash.

   Usage:
     node tools/build-data.js            # regenerate
     node tools/build-data.js --check    # CI: fail if generated files are stale
     node tools/build-data.js --report   # print the size table and exit
   ========================================================================== */
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'recipes-data.js');
const SHARDS = 16;

// DETAIL is an explicit deny-list and the INDEX is everything else — the
// inverse of how this was first written, and the change is load-bearing.
//
// With an allow-list for the index, any field not thought of simply vanished
// from the app: `subsection` (236 recipes; collection.js filters its sub-tabs
// on it) was dropped exactly that way, and nothing but the round-trip test in
// tools/test-mc-data.js noticed. Inverted, the failure mode flips to safe — a
// field added to recipes-data.js tomorrow ships in the index automatically,
// and the only way to lose one is to name it here on purpose.
//
// These three are heavy and are read only after a cook opens something:
// ingredients and instructions by recipe.html and the planner's grocery merge,
// `description` by exactly one place (cookbook.js's About card — nothing else
// renders it and recipesMatch() doesn't search it), which is worth ~51 KB.
const DETAIL_FIELDS = ['description', 'ingredients_by_serving', 'instructions'];

/* ── load the authored data exactly the way a browser does ──────────────── */
function loadSource() {
  const sandbox = { window: {} };
  sandbox.window.window = sandbox.window;
  vm.createContext(sandbox);
  vm.runInContext(fs.readFileSync(SRC, 'utf8'), sandbox);
  const R = sandbox.window.RECIPES, C = sandbox.window.COLLECTIONS;
  if (!Array.isArray(R) || !Array.isArray(C)) {
    console.error('::error::recipes-data.js did not define window.RECIPES and window.COLLECTIONS');
    process.exit(1);
  }
  return { RECIPES: R, COLLECTIONS: C };
}

// djb2. Any stable hash works; this one is short, has no dependencies, and
// spreads these particular 318 slugs evenly (verified: 31–66 KB per shard
// against the 211 KB worst case an alphabetical split produced).
function shardOf(id) {
  let h = 5381;
  for (let i = 0; i < id.length; i++) h = ((h * 33) ^ id.charCodeAt(i)) >>> 0;
  return h % SHARDS;
}

function pick(obj, fields) {
  const out = {};
  fields.forEach((f) => { if (obj[f] !== undefined) out[f] = obj[f]; });
  return out;
}
// Everything that isn't detail, in the recipe's own key order.
function omit(obj, fields) {
  const out = {};
  Object.keys(obj).forEach((k) => { if (fields.indexOf(k) < 0) out[k] = obj[k]; });
  return out;
}

const BANNER = (name) =>
  `/* ${name} — GENERATED by tools/build-data.js. Do not edit by hand.\n` +
  `   Edit recipes-data.js (the source of truth) and re-run the generator.\n` +
  `   CI fails on a stale copy: node tools/build-data.js --check */\n`;

/* ── generate ───────────────────────────────────────────────────────────── */
function generate() {
  const { RECIPES, COLLECTIONS } = loadSource();
  const files = {};

  const index = RECIPES.map((r) => {
    const e = omit(r, DETAIL_FIELDS);
    e._s = shardOf(r.recipe_id);
    return e;
  });

  files['recipes-index.js'] =
    BANNER('recipes-index.js') +
    'window.RECIPES_INDEX = ' + JSON.stringify(index) + ';\n' +
    'window.COLLECTIONS = ' + JSON.stringify(COLLECTIONS) + ';\n' +
    'window.RECIPES_SHARDS = ' + SHARDS + ';\n';

  const buckets = Array.from({ length: SHARDS }, () => ({}));
  RECIPES.forEach((r) => { buckets[shardOf(r.recipe_id)][r.recipe_id] = pick(r, DETAIL_FIELDS); });
  buckets.forEach((bucket, n) => {
    const name = 'recipes-detail-' + String(n).padStart(2, '0') + '.js';
    files[name] =
      BANNER(name) +
      'window.MCData._absorb(' + n + ',' + JSON.stringify(bucket) + ');\n';
  });

  return files;
}

/* ── modes ──────────────────────────────────────────────────────────────── */
const args = process.argv.slice(2);
const files = generate();

if (args.includes('--report')) {
  const total = Object.values(files).reduce((a, s) => a + Buffer.byteLength(s), 0);
  const src = fs.statSync(SRC).size;
  const idx = Buffer.byteLength(files['recipes-index.js']);
  const shardSizes = Object.keys(files).filter((f) => f !== 'recipes-index.js')
    .map((f) => Buffer.byteLength(files[f]));
  const kb = (b) => (b / 1024).toFixed(0) + ' KB';
  console.log('source recipes-data.js  ' + kb(src));
  console.log('recipes-index.js        ' + kb(idx) +
    '  (' + (100 * idx / src).toFixed(1) + '% of source — what a cold open now parses)');
  console.log('detail shards (' + SHARDS + ')      ' + kb(shardSizes.reduce((a, b) => a + b, 0)) +
    '  · largest ' + kb(Math.max(...shardSizes)) + ' · smallest ' + kb(Math.min(...shardSizes)));
  console.log('one recipe page         ' + kb(idx + Math.max(...shardSizes)) +
    '  worst case (index + biggest shard) vs ' + kb(src) +
    ' — ' + (100 - 100 * (idx + Math.max(...shardSizes)) / src).toFixed(0) + '% less');
  console.log('generated total         ' + kb(total));
  process.exit(0);
}

if (args.includes('--check')) {
  const stale = [];
  Object.keys(files).forEach((name) => {
    const p = path.join(ROOT, name);
    if (!fs.existsSync(p) || fs.readFileSync(p, 'utf8') !== files[name]) stale.push(name);
  });
  // A leftover shard from a previous, larger SHARDS count would be precached
  // and served forever; catch that too.
  fs.readdirSync(ROOT)
    .filter((f) => /^recipes-detail-\d+\.js$/.test(f) && !files[f])
    .forEach((f) => stale.push(f + ' (orphaned)'));

  if (stale.length) {
    console.error('::error::generated recipe data is stale: ' + stale.join(', '));
    console.error('Run: node tools/build-data.js');
    process.exit(1);
  }
  console.log('recipes-index.js + ' + SHARDS + ' detail shards are up to date.');
  process.exit(0);
}

Object.keys(files).forEach((name) => fs.writeFileSync(path.join(ROOT, name), files[name]));
fs.readdirSync(ROOT)
  .filter((f) => /^recipes-detail-\d+\.js$/.test(f) && !files[f])
  .forEach((f) => { fs.unlinkSync(path.join(ROOT, f)); console.log('removed orphaned ' + f); });
console.log('wrote recipes-index.js + ' + SHARDS + ' detail shards.');
